name: Run linter and tests on push
on:
    push:
        branches:
            - master
jobs:
    run-linter-and-tests:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              uses: npm i
              
            - name: Lint code
              run: npm run lint

            - name: Run tests
              run: npm test